package main

func init() {
	locpool.Resources["en"] = map[string]string{
		"commands.default.message.on.command": "Unknown command",
		"callbacks.error":                     "The state was lost 😢",
		"commands.default.message":            "It appears you haven't invoked any of the bot's support commands. Call /promo to create a promo code.",

		"commands.promo.description":  "Generate promo code for DickGrowerBot",
		"commands.get.description":    "Get promo codes table",
		"commands.stats.description":  "Get full promo codes statistics",
		"commands.edit.description":   "Edit an existing promo code",
		"commands.delete.description": "Delete an existing promo code",

		"commands.help.description":     "Show help",
		"commands.help.fields.language": "Choose your language:",

		"commands.language.description":     "Change language",
		"commands.language.fields.language": "Choose your language:",
		"commands.promo.fields.promo":       "Enter the promo code in a new message",
		"commands.promo.fields.length":      "Enter the length increase for the promo code",
		"commands.promo.fields.capacity":    "Enter the number of activations for the promo code",
		"commands.promo.fields.setDates":    "Would you like to set custom start and end dates?",
		"commands.promo.fields.since":       "Enter the start date (number of days, DD.MM.YYYY, or YYYY-MM-DD):",
		"commands.promo.fields.until":       "Enter the end date (number of days, DD.MM.YYYY, or YYYY-MM-DD):",
		"commands.promo.fields.code":        "Enter promo code(s) you want to view in a new message on one line, separated by space or comma",

		"messages.promo.created_full": "Promo code successfully created! Promo code: %s. Length bonus: %s. Activations: %s. Valid: %s — %s. Link: %s",
		"dateEndless":                 "endless",

		"fieldPromoCreated":   "Promo code created: ",
		"actionCreate":        "Create",
		"actionCancel":        "Cancel",
		"actionSetBothDates":  "Set both dates",
		"actionEndlessPromo":  "Endless promo",
		"actionFromNowToDate": "Temporary promo",
		"actionUpdate":        "Update",
		"textToCreate":        "Confirm promo code creation:",
		"textToUpdate":        "Confirm promo code update:",
		"promoCanceled":       "Promo code creation canceled",
		"promoUpdated":        "Promo code updated: %s",
		"promoDeleted":        "Promo code deleted",
		"promoDisabled":       "Promo code has already been activated %d times, so it was disabled instead of deleted",
		"errToCreatePromo":    "Error creating promo code",
		"errToUpdatePromo":    "Error updating promo code",
		"errToDeletePromo":    "Error deleting promo code",
		"errNoPermission":     "Access denied. Admin rights required",

		"noPromo": "No promo codes in the database or not found for the specific query",

		"listPromoCodesTitle":       "Promo codes",
		"listPromoCodesTotalEnding": "Total: %d promo codes",
		"listPromoCodesPageEnding":  "Page %d/%d · Total: %d promo codes",
		"listPromoSortCode":         "Code",
		"listPromoSortCapacity":     "Remaining",
		"listPromoSortSince":        "Start date",
		"responseCodeFormat":        "%s — %d cm (%d activations)",
		"statResponseCodeFormat":    "Promo code: %s — %d cm. Remaining activations: %d (Initial activations: %d, activations: %d)",
		"paginationExpired":         "This list has expired. Run /get again.",

		"BadLength":             "Enter a whole number for the length increase (for example, 10)",
		"BadCapacity":           "Enter a positive whole number of activations (for example, 10)",
		"BadSince":              "Invalid start date. Use a number of days, DD.MM.YYYY, or YYYY-MM-DD",
		"BadUntil":              "Invalid end date. Use a number of days, DD.MM.YYYY, or YYYY-MM-DD",
		"promoCodeRequired":     "Promo code cannot be empty",
		"promoLengthNonZero":    "Length increase cannot be zero",
		"promoCapacityPositive": "Number of activations must be greater than zero",
		"promoUntilNotPast":     "End date cannot be in the past",
		"promoUntilAfterSince":  "End date must be later than the start date",
		"statsCodesRequired":    "Enter at least one promo code",
		"deleteUsage":           "Usage: /delete CODE",

		"success": "👍🏼",
		"failure": "Something went wrong...",

		"invalid": "Invalid arguments",

		"groupCommandsDisabled": "My commands work in direct messages only. Write to me privately and call /help.",

		"reportTitle":                   "📊 Promo code report since %s",
		"reportSectionCreated":          "🆕 Created",
		"reportSectionActivated":        "✅ Activated",
		"reportSectionNotActivated":     "💤 Never activated",
		"reportSectionCount":            "Total: %d",
		"reportEntryCreatedFormat":      "%s — by %s, %d cm, %d activations, created %s, valid: %s — %s",
		"reportEntryActivatedFormat":    "%s — %d activations",
		"reportEntryNotActivatedFormat": "%s",
		"reportEmpty":                   "📊 No promo codes have been created since %s.",
		"reportUnknownAuthor":           "unknown",

		"reportPageSuffix": "%s (page %d)",
		"reportDateLayout": "2006-01-02",
		"reportTruncated":  "… and %d more page(s) were left out. Raise REPORT_MAX_PAGES to see them.",

		"eventsReportTitle":         "👥 Promo code changes since %s",
		"eventsReportEmpty":         "👥 No promo codes were changed since %s.",
		"eventsReportAuthor":        "👤 %s",
		"eventsReportEntryFormat":   "%s %s %s",
		"eventsReportChangesFormat": ": %s",
		"eventsReportChangeFormat":  "%s %s → %s",
		"eventsTimeLayout":          "2006-01-02 15:04",
		"eventsActionCreate":        "created",
		"eventsActionUpdate":        "updated",
		"eventsActionDelete":        "deleted",
		"eventsFieldBonusLength":    "length",
		"eventsFieldSince":          "start date",
		"eventsFieldUntil":          "end date",
		"eventsFieldCapacity":       "activations",

		"user":   "user",
		"author": "author",
		"admin":  "admin",
	}

	locpool.Resources["ru"] = map[string]string{
		"commands.default.message.on.command": "Неизвестная команда",
		"callbacks.error":                     "Состояние формы потерялось 😢",
		"commands.default.message":            "Кажется, вы не вызвали ни одной команды, которую поддерживает бот. Вызовите /promo для создания промокода.",

		"commands.promo.description":  "Создать промокод для DickGrowerBot",
		"commands.get.description":    "Получить таблицу промокодов",
		"commands.stats.description":  "Получить полную статистику по промокодам",
		"commands.edit.description":   "Изменить существующий промокод",
		"commands.delete.description": "Удалить существующий промокод",

		"commands.help.description":     "Показать помощь",
		"commands.help.fields.language": "Выберите свой язык:",

		"commands.language.description": "Сменить язык пользования",

		"commands.language.fields.language": "Выберите свой язык:",
		"commands.promo.fields.promo":       "Введите промокод новым сообщением",
		"commands.promo.fields.length":      "Введите прибавку к длине для создания промокода",
		"commands.promo.fields.capacity":    "Введите количество активаций промокода",
		"commands.promo.fields.setDates":    "Хотите задать даты начала и окончания?",
		"commands.promo.fields.since":       "Введите дату начала (количество дней, ДД.ММ.ГГГГ или ГГГГ-ММ-ДД):",
		"commands.promo.fields.until":       "Введите дату окончания (количество дней, ДД.ММ.ГГГГ или ГГГГ-ММ-ДД):",
		"commands.promo.fields.code":        "Введите промокод(ы), которые хотите просмотреть, новым сообщением в одну строчку через пробел или запятую",

		"fieldPromoCreated":   "Промокод создан: ",
		"actionCreate":        "Создать",
		"actionCancel":        "Отменить",
		"actionSetBothDates":  "Задать обе даты",
		"actionEndlessPromo":  "Бессрочный",
		"actionFromNowToDate": "Временный",
		"actionUpdate":        "Обновить",
		"textToCreate":        "Подтвердите создание промокода:",
		"textToUpdate":        "Подтвердите изменение промокода:",
		"promoCanceled":       "Создание промокода отменено",
		"promoUpdated":        "Промокод изменен: %s",
		"promoDeleted":        "Промокод удален",
		"promoDisabled":       "Промокод отключен вместо удаления. Количество активаций: %d",
		"errToCreatePromo":    "Ошибка при создании промокода",
		"errToUpdatePromo":    "Ошибка при изменении промокода",
		"errToDeletePromo":    "Ошибка при удалении промокода",
		"errNoPermission":     "Доступ запрещен. Требуются права администратора",

		"messages.promo.created_full": "Промокод успешно создан! Промокод: %s. Прибавка к длине: %s. Активаций: %s. Действует: %s — %s. Ссылка: %s",
		"dateEndless":                 "бессрочно",

		"noPromo": "Нет промокодов в базе или не найдены по конкретному запросу",

		"listPromoCodesTitle":       "Промокоды",
		"listPromoCodesTotalEnding": "Всего: %d промокодов",
		"listPromoCodesPageEnding":  "Страница %d/%d · Всего: %d промокодов",
		"listPromoSortCode":         "Код",
		"listPromoSortCapacity":     "Остаток",
		"listPromoSortSince":        "Дата",
		"responseCodeFormat":        "%s — %d см (%d активаций)",
		"statResponseCodeFormat":    "Промокод: %s — %d см. Осталось использований: %d (Изначальное кол-во использований: %d, активаций: %d)",
		"paginationExpired":         "Список устарел. Вызовите /get ещё раз.",

		"success": "👍🏼",
		"failure": "Что-то пошло не так...",

		"invalid": "Неверные аргументы",

		"BadLength":             "Введите целое число для прибавки к длине, например 10",
		"BadCapacity":           "Введите положительное целое число активаций, например 10",
		"BadSince":              "Неверная дата начала. Используйте количество дней, ДД.ММ.ГГГГ или ГГГГ-ММ-ДД",
		"BadUntil":              "Неверная дата окончания. Используйте количество дней, ДД.ММ.ГГГГ или ГГГГ-ММ-ДД",
		"promoCodeRequired":     "Промокод не может быть пустым",
		"promoLengthNonZero":    "Прибавка к длине не может быть равна нулю",
		"promoCapacityPositive": "Количество активаций должно быть больше нуля",
		"promoUntilNotPast":     "Дата окончания не может быть в прошлом",
		"promoUntilAfterSince":  "Дата окончания должна быть позже даты начала",
		"statsCodesRequired":    "Укажите хотя бы один промокод",
		"deleteUsage":           "Формат: /delete CODE",

		"groupCommandsDisabled": "Мои команды работают только в личных сообщениях. Напишите мне в личку и вызовите /help.",

		"reportTitle":                   "📊 Отчёт по промокодам с %s",
		"reportSectionCreated":          "🆕 Созданы",
		"reportSectionActivated":        "✅ Активированы",
		"reportSectionNotActivated":     "💤 Ни разу не активированы",
		"reportSectionCount":            "Всего: %d",
		"reportEntryCreatedFormat":      "%s — автор %s, %d см, %d активаций, создан %s, действует: %s — %s",
		"reportEntryActivatedFormat":    "%s — %d активаций",
		"reportEntryNotActivatedFormat": "%s",
		"reportEmpty":                   "📊 С %s не было создано ни одного промокода.",
		"reportUnknownAuthor":           "неизвестен",

		"reportPageSuffix": "%s (страница %d)",
		"reportDateLayout": "02.01.2006",
		"reportTruncated":  "… и ещё %d страниц(ы) не поместились. Увеличьте REPORT_MAX_PAGES, чтобы увидеть их.",

		"eventsReportTitle":         "👥 Изменения промокодов с %s",
		"eventsReportEmpty":         "👥 С %s промокоды не изменялись.",
		"eventsReportAuthor":        "👤 %s",
		"eventsReportEntryFormat":   "%s %s %s",
		"eventsReportChangesFormat": ": %s",
		"eventsReportChangeFormat":  "%s %s → %s",
		"eventsTimeLayout":          "02.01.2006 15:04",
		"eventsActionCreate":        "создал",
		"eventsActionUpdate":        "изменил",
		"eventsActionDelete":        "удалил",
		"eventsFieldBonusLength":    "прибавка",
		"eventsFieldSince":          "дата начала",
		"eventsFieldUntil":          "дата окончания",
		"eventsFieldCapacity":       "активации",

		"user":   "обычный",
		"author": "автор",
		"admin":  "админ",
	}
}
